Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "aerospike/centos-6.5"
    web.vm.hostname = 'web'
    web.vm.network "public_network", bridge: "eno0"
  end

  config.vm.define "db" do |db|
    db.vm.box = "aerospike/centos-6.5"
    db.vm.hostname = 'db'
    db.vm.network "public_network", bridge: "eno1"
  end
end
